version: '2.3'

networks:
  tanner_snare_connect:
    external: true

services:

# Snare target service (the proxied website)
  target:
    container_name: snare-target
    restart: unless-stopped
    tty: true
    networks:
     - tanner_snare_connect
    image: kimbtechnologies/kimb_forms_project:latest
    environment:
      - CONF_site_hosturl=
      - CONF_site_pagename=KIMB-Forms-Project Target
      - CONF_site_footercontent=Snare based target
      - CONF_captcha_poll=false
      - CONF_captcha_new=false
      - CONF_texts_enablePoll=false
      - CONF_texts_enableNew=true
      - CONF_texts_textPoll=Ich bin mit den Datenschutzrichtlinien ... einverstanden!
      - CONF_texts_textNew=Ich bin mit den AGB des Anbieters einverstanden!
      - CONF_cookiebanner=false
      - CONF_newpollmailto=test@example.com # admin mail, get mail when a poll is created
      - CONF_submissions_enabled=false # query for poll submissions by mail
      - CONF_submissions_captcha=true # query needs captcha
      - CONF_submissions_mailValidate=^\S+@\S+\.\S+$$ # query mail address validation
      - SMTP_SERVER= # the mail server host (used for admin notification mails)
      - SMTP_PORT= # the port to deliver mails (587 for starttls or 465 for tls)
      - SMTP_USER= # the username for the mail server
      - SMTP_PASS= # the password for the mail server
    cpu_count: 2
    mem_limit: 1G
