version: '2.3'

networks:
  tanner_local:
  snare_connect:

services:

# Tanner Redis Service
  tanner_redis:
    build: ./redis
    container_name: tanner_redis
    restart: unless-stopped
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    read_only: true
    cpu_count: 1
    mem_limit: 1G

# PHP Sandbox service
  tanner_phpox:
    build: ./phpox
    container_name: tanner_phpox
    restart: unless-stopped
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    read_only: true
    tmpfs: "/tmp"
    cpu_count: 1
    mem_limit: 1G

# Alpine Sandbox (Telnet access)
  tanner_alpine:
    build: ./alpine
    container_name: tanner_alpine
    restart: unless-stopped
    stop_signal: SIGKILL
    tty: true
    networks:
     - tanner_local
    read_only: true
    cpu_count: 1
    mem_limit: 500M

# Tanner API Service
  tanner_api:
    build: ./tanner
    container_name: tanner_api
    restart: unless-stopped
    stop_signal: SIGKILL
    tmpfs:
     - /tmp/tanner:uid=65534,gid=65534
     - /var/log/tanner:uid=65534,gid=65534
    tty: true
    networks:
     - tanner_local
    read_only: true
    command: tannerapi 
    depends_on:
     - tanner_redis
    cpu_count: 2
    mem_limit: 4G

# Tanner WEB Service
  tanner_web:
    build: ./tanner
    container_name: tanner_web
    restart: unless-stopped
    stop_signal: SIGKILL
    tmpfs:
     - /tmp/tanner:uid=65534,gid=65534
     - /var/log/tanner:uid=65534,gid=65534
    tty: true
    networks:
     - tanner_local
    ports:
     - "8091:8091"
    command: tannerweb
    read_only: true
    depends_on:
     - tanner_redis
    cpu_count: 2
    mem_limit: 4G

# Tanner Service
  tanner:
    build: ./tanner
    container_name: tanner
    restart: unless-stopped
    stop_signal: SIGKILL
    tmpfs:
     - /tmp/tanner:uid=65534,gid=65534
     - /var/log/tanner:uid=65534,gid=65534
     - /opt/tanner/files:uid=65534,gid=65534
    tty: true
    networks:
     - tanner_local
     - snare_connect
    ports:
     - "8090:8090"
    command: tanner
    read_only: true
    depends_on:
     - tanner_api
     - tanner_web
     - tanner_phpox
    cpu_count: 3
    mem_limit: 4G
